# Generated by Django 2.0.6 on 2021-08-07 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
            ],
            options={
                'verbose_name': 'アルバイト',
                'verbose_name_plural': 'アルバイト',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField(null=True)),
                ('end_at', models.DateTimeField(null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shift.employee')),
            ],
            options={
                'verbose_name': 'シフト予定表',
                'db_table': 'schedule',
            },
        ),
    ]
