# Generated by Django 2.0.6 on 2021-08-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0003_auto_20210807_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='employee_id',
            new_name='employee_name',
        ),
    ]
