# Generated by Django 3.1.6 on 2021-02-06 01:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='kakeibo',
            managers=[
                ('count', django.db.models.manager.Manager()),
            ],
        ),
    ]
