# Generated by Django 3.1.6 on 2021-02-06 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0002_auto_20210206_1001'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='kakeibo',
            managers=[
            ],
        ),
    ]
